<!DOCTYPE html>
<html lang="en">
	<!--
	Meta tags + Link to style sheet + Title of Page.
	-->
	<head>
	<?php
        include 'header.inc';
        ?>
    <link rel="stylesheet" href="styles/styles.css">
	<title>Home Page</title>
	</head>
    
	<body id="index">
		
		<!--
		Menu Below that connects to all the pages and has an email link to fake email for company
		-->
    	<?php
        include 'nav.inc';
        ?>
		<hr>
		<!--
		Fake information generated by chatgpt about a company that would be hiring G04 - Cybersecurity Specialist
    	G05 - IT Support Technician, also fake logo for "Shield Tech" 
		-->
		<h1>Tech Shield</h1>
		<div id="introduction">
    		<img src="styles/images/tech.jpg" alt="Logo"> 
			<div id="logo">
				<P>Tech Shield is a forward-thinking IT solutions provider committed to protecting digital assets and powering
				business operations with expert technical support. Built on a foundation of innovation, trust, and performance, 
				Tech Shield has become a go-to technology partner for organizations seeking both security and reliability in 
				their IT infrastructure.<br>We specialize in two core areas:</p>
				<img src="styles/images/logo.png" alt="Logo"> 
			</div>
		</div>
		<h2>🔐 Cybersecurity Services:</h2>
		<p>Our Cybersecurity Specialists design and deploy intelligent defense systems to counteract today’s most 
		advanced cyber threats. From real-time threat monitoring to incident response and compliance strategies, 
		we help businesses stay ahead of hackers and vulnerabilities with proactive, tailored security solutions.</p>
		<h2>🛠️ IT Support & Infrastructure:</h2>
		<p>Our IT Support Technicians keep everything running smoothly behind the scenes. Whether it’s resolving
		hardware issues, managing network systems, or supporting cloud environments, they provide fast, dependable,
		and user-friendly tech support that keeps businesses moving forward without interruption.</p>
		<!--
		Footer below with link to jira project.
		-->
		<footer>
			<?php
        include 'footer.inc';
        ?>
		
		</footer> 
    </body>
	